[package]
name = "common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
json = { path = "../../libs/json" }
logger = { path = "../../libs/logger" }
rekuest = { path = "../../libs/rekuest" }
