[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
common = { path = "../common" }
ehandle = { path = "../ehandle" }
logger = { path = "../../libs/logger" }
min-sqlite3-sys = "1.4"
sql-builder = { path = "../../libs/sql-builder" }