name: lpm
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: check code format and lint
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features -- --D warnings

  test:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: unit tests
        run: |
          cargo test --all-features

      - name: build lpm
        run: |
          cargo build

      - name: lpm --update --all
        run: |
          sudo ./target/debug/lpm --update --all

      - name: Sync with 'linux-amd64-default' repository
        run: |
          sudo ./target/debug/lpm --repository --add linux-amd64-default linux-amd64-default.lodpm.com
          sudo ./target/debug/lpm --update --index

      - name: lpm --install
        run: |
          sudo ./target/debug/lpm --install lzip
          sudo ./target/debug/lpm --install gc-devel

      - name: lpm --delete
        run: |
          sudo ./target/debug/lpm --delete lzip
          sudo ./target/debug/lpm --delete gc-devel


  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          cargo build --all-features
