name: lpm
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: check code format and lint
        run: |
          cargo fmt --all -- --check
          cargo clippy --all-targets --all-features -- --D warnings

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          cargo test --all-features

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cargo build --all-features
