name: sdk pipeline
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable-2022-08-11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --manifest-path sdk/Cargo.toml

  fmt:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable-2022-08-11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all --manifest-path sdk/Cargo.toml -- --check

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable-2022-08-11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: clippy
    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --manifest-path sdk/Cargo.toml -- -D warnings

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable-2022-08-11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path sdk/Cargo.toml

  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable-2022-08-11]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path sdk/Cargo.toml
